# Generated by Django 5.1.3 on 2024-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassengerManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='review_date',
            field=models.DateField(blank=True),
        ),
    ]
