# Generated by Django 5.1.3 on 2024-11-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassengerManagement', '0002_alter_driver_active_alter_driver_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PassengerManagement.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PassengerManagement.vehicle'),
        ),
    ]
