# Generated by Django 5.1.3 on 2024-11-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassengerManagement', '0003_remove_trip_passengers_remove_trip_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, to='PassengerManagement.passenger'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In progress'), ('completed', 'Completed')], default='planned', max_length=50),
        ),
    ]
