# Generated by Django 5.1.3 on 2024-11-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassengerManagement', '0004_trip_passengers_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='passengers',
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=50),
        ),
    ]
