# Generated by Django 5.1.3 on 2024-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassengerManagement', '0005_remove_trip_passengers_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(to='PassengerManagement.passenger'),
        ),
    ]
