# Generated by Django 5.1.3 on 2024-11-30 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassengerManagement', '0007_trip_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PassengerManagement.passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='PassengerManagement.trip')),
            ],
        ),
    ]
